services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: diario-backend
    env_file:
      - ./backend/.env
    environment:
      PORT: 3001
      DB_DIALECT: sqlite
      DB_STORAGE: /data/dev.sqlite
      FRONT_ORIGIN: http://localhost:8080
    volumes:
      - backend-data:/data
      - backend-uploads:/app/uploads
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:3001/api/v2
    container_name: diario-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data:
  backend-uploads:
